config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  
  devise_scope :user do
    authenticated do
      root to: "clients#index"
    end
    
    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end
  
  resources :estimates do
    resources :estimate_items, except: [:index], controller: 'estimates/estimate_items'
    member do
      get :estimate_pdf
      get :view_estimate_pdf
    end
    collection { get :generate_estimate_pdfs }
  end
  
  resources :payments
  resources :services
  
  resources :clients do
    member do
      get :reminder
    end

    collection do
      post :import
      get :summary
      get :generate_reminders
      get :reminder_labels
    end
    
    resources :client_prices, except: [:index], controller: 'clients/client_prices' do
      collection { post :import }
    end
    
  end
  
  resources :invoices do
    resources :invoice_items, except: [:index], controller: 'invoices/invoice_items'
    member do
      put :set_sent
      put :set_paid
      get :show_pdf
      get :generate_pdf
    end
    collection do
      get :generate_multiple_pdfs
      get :labels
    end
  end
  
  resources :client_prices, controller: 'clients/client_prices' do
    collection { post :import }
  end
  
end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
  belongs_to :client
  has_many :estimate_items
  
  def client_name
  end
  
  def client_name=(name)
  end
  
end

app/controllers/estimates/estimate_items_controller.rb
class Estimates::EstimateItemsController < ApplicationController
  # GET /estimate_items
  # GET /estimate_items.json
  def index
    @estimate_items = EstimateItem.all
  end

  # GET /estimate_items/1
  # GET /estimate_items/1.json
  def show
  end

  # GET /estimate_items/new
  def new
    @estimate = Estimate.find(params[:estimate_id])
    @estimate_item = EstimateItem.new
  end

  # GET /estimate_items/1/edit
  def edit
  end

  # POST /estimate_items
  # POST /estimate_items.json
  def create
    @estimate = Estimate.find(params[:estimate_id])
    @estimate_item = EstimateItem.new(estimate_item_params)
    @estimate_item.estimate = @estimate
    
    @estimate.update_attribute :total, @estimate.total + (@estimate_item.price * @estimate_item.quantity)

    respond_to do |format|
      if @estimate_item.save
        format.html { redirect_to @estimate, notice: 'Estimate item was successfully created.' }
        format.json { render :show, status: :created, location: @estimate }
      else
        format.html { render :new }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estimate_items/1
  # PATCH/PUT /estimate_items/1.json
  def update
    respond_to do |format|
      if @estimate_item.update(estimate_item_params)
        format.html { redirect_to @estimate_item, notice: 'Estimate item was successfully updated.' }
        format.json { render :show, status: :ok, location: @estimate_item }
      else
        format.html { render :edit }
        format.json { render json: @estimate_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estimate_items/1
  # DELETE /estimate_items/1.json
  def destroy
    @estimate = Estimate.find(params[:estimate_id])
    @estimate_item = EstimateItem.find(params[:id])
    
    @estimate.update_attribute :total, @estimate.total - (@estimate_item.price * @estimate_item.quantity)
    
    if @estimate_item.destroy
      flash[:notice] = "#{@estimate_item.name} was deleted succesfully."
      redirect_to @estimate
    else
      flash[:error] = "There was an error deleting the item."
      render :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estimate_item
      @estimate_item = EstimateItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estimate_item_params
      params.require(:estimate_item).permit(:estimate_id, :name, :price, :quantity)
    end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_filter :authenticate_user!, :except => [:estimate_pdf, :view_estimate_pdf, :generate_estimate_pdf]
  before_action :set_estimate, only: [:show, :edit, :update, :destroy]

  # GET /estimates
  # GET /estimates.json
  def index
    @estimates = Estimate.all
  end

  # GET /estimates/1
  # GET /estimates/1.json
  def show
    @estimate = Estimate.find(params[:id])
    @estimate_items = @estimate.estimate_items
  end

  # GET /estimates/new
  def new
    @estimate = Estimate.new
  end

  # GET /estimates/1/edit
  def edit
  end

  # POST /estimates
  # POST /estimates.json
  def create
    @estimate = Estimate.new(estimate_params)

    respond_to do |format|
      if @estimate.save
        format.html { redirect_to @estimate, notice: 'Estimate was successfully created.' }
        format.json { render :show, status: :created, location: @estimate }
      else
        format.html { render :new }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estimates/1
  # PATCH/PUT /estimates/1.json
  def update
    respond_to do |format|
      if @estimate.update(estimate_params)
        format.html { redirect_to @estimate, notice: 'Estimate was successfully updated.' }
        format.json { render :show, status: :ok, location: @estimate }
      else
        format.html { render :edit }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estimates/1
  # DELETE /estimates/1.json
  def destroy
    @estimate.destroy
    respond_to do |format|
      format.html { redirect_to estimates_url, notice: 'Estimate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def estimate_pdf
    @estimate = Estimate.find(params[:id])
    @estimate_items = @estimate.estimate_items
    
    render :layout => 'pdf_layout'
  end
  
  def view_estimate_pdf
    @estimate = Estimate.find(params[:id])
    path = estimate_pdf_estimate_url(@estimate)
    filename = "estimate_#{@estimate.id}"
    
    kit = PDFKit.new(path)
    pdf = kit.to_pdf
    send_data(pdf, :filename => filename, :type => 'application/pdf', :disposition => 'inline')
  end
  
  def generate_estimate_pdfs
    #generate pdfs from selected invoices and save each to file
    @estimates = Estimate.find(params[:selected_estimates])
    files = []
    @estimates.each do |estimate|
      path = estimate_pdf_estimate_url(estimate)
      filename = "estimate_#{estimate.id}.pdf"
      files.push filename    
      
      kit = PDFKit.new(path)
      pdf = kit.to_file("#{Rails.root}/public/estimates/#{filename}")
    end
    
    #Combine generated PDFs into single file
    pdf_pack = CombinePDF.new
    files.each do |file|
      pdf_pack << CombinePDF.load("#{Rails.root}/public/estimates/#{file}")
    end
    pack_filename = "estimates#{Date.today.to_formatted_s(:iso8601)}.pdf"
    pdf_pack.save "#{Rails.root}/public/estimates/#{pack_filename}"
    
    send_file("#{Rails.root}/public/estimates/#{pack_filename}", :type => 'application/pdf', :disposition => 'inline')
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estimate
      @estimate = Estimate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estimate_params
      params.require(:estimate).permit(:date, :total, :notes, :client_id)
    end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_form.html.erb
<%= form_for(@estimate) do |f| %>
  <% if @estimate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estimate.errors.count, "error") %> prohibited this estimate from being saved:</h2>

      <ul>
      <% @estimate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, :default => Date.today %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total, required: true %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes, required: true %>
  </div>
  <div class="field">
    <%= f.label :client %><br>
    <%= f.text_field :client_name, data: {autocomplete_source: Client.order(:last_name).map{ |m| {:label=>m.client_summary, :id=>m.id}}}, required: true %>
    <%= f.hidden_field :client_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estimates/edit.html.erb
<h1>Editing Estimate</h1>

<%= render 'form' %>

<%= link_to 'Show', @estimate %> |
<%= link_to 'Back', estimates_path %>

app/views/estimates/estimate_pdf.html.erb
<div>
  <div>
    <p>
      <h2> <u>Moffa Landscaping</u>
        </h2>
      1647 Northshore Road<br>
      Revere, MA 02151
      </p>
  </div>
  <br>
  <h3> 
    Invoice
    </h3>
  <br>
  <div class="pull-left" style="width:33%">
    <p> 
      <%= @estimate.client.first_name %> <%= @estimate.client.last_name %> <br>
      <%= @estimate.client.billing_address %> <br>
      <%= @estimate.client.city %>, <%= @estimate.client.state %> <%= @estimate.client.zip %>   
      </p>
    </div>

  <div class="pull-right" style="width:33%">
    <p> 
      <strong>Estimate number:</strong> <%= @estimate.id %> <br>
      <strong>Estimate date:</strong> <%= @estimate.date.strftime("%m-%d-%y") %> <br>
      </p>
    </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <div>
    <p>
      <strong>Notes:</strong>
      </p>
    <br>
    <div class="panel panel-default" >
      <div class="panel-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Service</th>
              <th>Quantity</th>
              <th>Cost</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>
            <% @estimate_items.each do |item| %>
            <tr>
              <% if item.name.downcase == 'cut' %>
                <td><h4><%= @estimate.date.strftime( "%B" ) %> Lawncare</h4></td>
                <% else %>
                <td><h4><%= item.name %></h4></td>
                <%end %>
                <td><h4><%= item.quantity %></h4></td>
              <% if item.price == 0 %>
                <td><h4>-</h4></td>
                <td><h4>-</h4></td>              
              <% else %>
                <td><h4><%= number_to_currency(item.price) %> </h4></td>
                <td><h4><%= number_to_currency(item.price * item.quantity) %> </h4></td>
              <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        <br>
        <h4 class='pull-right' align='right'>
          <strong>Estimate Total:</strong> <%= number_to_currency(@estimate.total) %>
        </h4>
      </div>
    </div>
  </div>
  
  <br>

  
</div>

app/views/estimates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Estimates</h1>

<div class="media">
  <div class="media-body">
  <%= form_tag generate_estimate_pdfs_estimates_path, method: :get do %>
	<table class="table table-hover">
	  <thead>
	    <tr>
        <th><input type="checkbox" id="selectAll" value="selectAll"></th>
	      <th>Date</th>
	      <th>Total</th>
	      <th>Notes</th>
	      <th>Client</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @estimates.each do |estimate| %>
	      <tr>
          <td><%= check_box_tag "selected_estimates[]", estimate.id %></td>
          <td><%= estimate.date.strftime("%m-%d-%y") %></td>
          <td><%= estimate.total %></td>
          <td><%= estimate.notes %></td>
          <td><%= estimate.client.first_name %> <%= estimate.client.last_name %></td>
          <td><%= link_to 'Show', estimate, class: 'btn btn-mini btn-default' %></td>
          <td><%= link_to 'Edit', edit_estimate_path(estimate), class: 'btn btn-mini btn-success' %></td>
          <td><%= link_to 'Destroy', estimate, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
	      </tr>
      <% end %>
	  </tbody>
	</table>
    <%= submit_tag "Print Selected" %>
  <% end %>
  </div>
</div>

<br>

<%= link_to 'New Estimate', new_estimate_path %>

<script>
  $('#selectAll').click(function() {
     if (this.checked) {
         $(':checkbox').each(function() {
             this.checked = true;                        
         });
     } else {
        $(':checkbox').each(function() {
             this.checked = false;                        
         });
     } 
  });
</script>

app/views/estimates/new.html.erb
<h1>New Estimate</h1>

<%= render 'form' %>

<%= link_to 'Back', estimates_path %>

app/views/estimates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @estimate.date %>
</p>

<p>
  <strong>Client:</strong>
  <%= @estimate.client.first_name %> <%= @estimate.client.last_name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @estimate.notes %>
</p>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Service</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Total</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @estimate_items.each do |item| %>
        <tr>
          <td><h4><%= item.name  %></h4></td>
          <td><h4><%= item.quantity %></h4></td>
          <td><h4><%= number_to_currency(item.price) %></h4></td>
          <td><h4><%= number_to_currency(item.price * item.quantity) %> </h4></td> 
          <td><h4><%= link_to "Delete", [@estimate, item], method: :delete, confirm: "Are you sure you want to delete this item?" %></h4></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to "Add new item", new_estimate_estimate_item_path(@estimate), class: 'pull-right' %>

<br>

<h4 class='pull-right'> Estimate total: <%= number_to_currency(@estimate.total) %> </h4>

<%= link_to 'Edit', edit_estimate_path(@estimate) %> |
<%= link_to 'Back', estimates_path %> |
<%= link_to 'Generate PDF', view_estimate_pdf_estimate_path(@estimate) %>