config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  
  devise_scope :user do
    authenticated do
      root to: "clients#index"
    end
    
    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end
  
  resources :estimates do
    resources :estimate_items, except: [:index], controller: 'estimates/estimate_items'
    member do
      get :estimate_pdf
      get :view_estimate_pdf
    end
    collection { get :generate_estimate_pdfs }
  end
  
  resources :payments
  resources :services
  
  resources :clients do
    member do
      get :reminder
    end

    collection do
      post :import
      get :summary
      get :generate_reminders
      get :reminder_labels
    end
    
    resources :client_prices, except: [:index], controller: 'clients/client_prices' do
      collection { post :import }
    end
    
  end
  
  resources :invoices do
    resources :invoice_items, except: [:index], controller: 'invoices/invoice_items'
    member do
      put :set_sent
      put :set_paid
      get :show_pdf
      get :generate_pdf
    end
    collection do
      get :generate_multiple_pdfs
      get :labels
    end
  end
  
  resources :client_prices, controller: 'clients/client_prices' do
    collection { post :import }
  end
  
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  has_many :invoice_items, dependent: :destroy
  validates :client_id, presence: true
  
  def client_name
  end
  
  def client_name=(name)
  end
  
  def check_balance_forward
    if (client.balance == 0)
      'pos_balance'      
    elsif (balance_forward < 0)
    	'neg_balance'
    else
      'pos_balance'
    end
  end

  def balance_forward
    if client.balance == 0
      0
    else
      (client.balance - total)
    end
  end
		
	def amount_due
    total + balance_forward
  end

  def invoice_summary
    [date.strftime("%m/%d/%y"), client.last_name, ("$"+total.to_s)].join (' - ')
  end
  
  def build_pdf
    path = show_pdf_invoice_url(self)
    filename = "invoice_#{self.id}"
    
    kit = PDFKit.new(path)
    pdf = kit.to_pdf
    send_data(pdf, :filename => filename, :type => 'application/pdf', :disposition => 'inline')
  end
  
end

app/controllers/invoices/invoice_items_controller.rb
class Invoices::InvoiceItemsController < ApplicationController

  def index
    @invoice_items = InvoiceItem.all
  end

  def show
  end

  def new
    @invoice = Invoice.find(params[:invoice_id])
    
    unless @invoice.status == "PENDING"
      respond_to do |format|
        format.html { redirect_to @invoice, notice: "Invoice has already been finalized! You can't add more items!" }
        format.json { head :no_content }
      end
    else    
      @invoice_item = InvoiceItem.new
      @client = @invoice.client.id
    
      @client_prices = ClientPrice.where(:client_id => @client)
    end
    
  end

  def edit
  end

  def create    
    @invoice = Invoice.find(params[:invoice_id])
    @invoice_item = InvoiceItem.new(invoice_item_params)
    @invoice_item.invoice = @invoice
    
    @client = Client.find(@invoice.client.id)
    @invoice_item.client_id = @client.id
  
    unless params[:other_service_name].empty? 
      @invoice_item.name = params[:other_service_name]
    end
    
    unless params[:new_price].empty?
      @invoice_item.price = params[:new_price]
      @invoice.update_attribute :total,  @invoice.total + (@invoice_item.price * @invoice_item.quantity)
      @client.update_attribute :balance, (@client.balance + (@invoice_item.price * @invoice_item.quantity))
    else
      @client_price = ClientPrice.find_by name: @invoice_item.name, client_id: @invoice_item.client_id 
      @invoice_item.price = @client_price.price
      @invoice.update_attribute :total,  @invoice.total + (@invoice_item.price * @invoice_item.quantity)
      @client.update_attribute :balance, (@client.balance + (@invoice_item.price * @invoice_item.quantity))
      
    end
      
      
    
    respond_to do |format|
      if @invoice_item.save
        format.html { redirect_to @invoice, notice: 'Invoice item was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @invoice_item.update(invoice_item_params)
        format.html { redirect_to @invoice_item, notice: 'Invoice item was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_item }
      else
        format.html { render :edit }
        format.json { render json: @invoice_item.errors, status: :unprocessable_entity }
      end
    end
  end

def destroy
    @invoice = Invoice.find(params[:invoice_id])
    
  if @invoice.status == "PENDING"
    @invoice_item = InvoiceItem.find(params[:id])
    @client = Client.find(@invoice.client.id)
    title = @invoice_item.name
    
    @invoice.update_attribute :total,  @invoice.total - (@invoice_item.price * @invoice_item.quantity)
    @client.update_attribute :balance, (@client.balance - (@invoice_item.price * @invoice_item.quantity))
    
    if @invoice_item.destroy
      flash[:notice] = "#{title} was deleted succesfully."
      redirect_to @invoice
    else
      flash[:error] = "There was an error deleting the item from the invoice."
      render :show
    end
  else
    respond_to do |format|
      format.html { redirect_to @invoice, notice: "You can no longer modify this invoice!" }
      format.json { head :no_content }
    end
  end
    
end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_item
      @invoice_item = InvoiceItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_item_params
      params.require(:invoice_item).permit(:name, :category, :quantity, :invoice_id, :price, :client_id, :other_service_name, :new_price)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show_pdf, :generate_pdf, :generate_multiple_pdfs, :labels]
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /invoices
  # GET /invoices.json
  def index
    @search = InvoiceSearch.new(params[:search])
    @invoices = @search.scope.order(sort_column + " " + sort_direction)
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])
    @invoice_items = @invoice.invoice_items
    @client_prices = ClientPrice.where(:client_id => @invoice.client.id)
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new    
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.status = "PENDING"
    @invoice.total = 0

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    if @invoice.status == "SENT" || @invoice.status == "PAID"
      respond_to do |format|
        format.html { redirect_to @invoice, notice: "Invoice has already been #{@invoice.status}!" }
        format.json { head :no_content }
      end
    else
      @invoice.destroy
      respond_to do |format|
        format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end
  
  def set_sent
    @invoice = Invoice.find(params[:id])
    
    if @invoice.status == "SENT"
      respond_to do |format|
        format.html { redirect_to @invoice, notice: "Invoice has already been #{@invoice.status}!" }
        format.json { head :no_content }
      end
    elsif @invoice.status == "PAID"
        respond_to do |format|
          format.html { redirect_to @invoice, notice: 'Invoice has already been PAID!' }
          format.json { head :no_content }
        end
    else    
      @invoice.update_attribute :status, "SENT"
      flash[:notice] = "Invoice marked as '#{@invoice.status}'!"
      redirect_to @invoice
    end
  end
  
  def set_multiple_sent(invoices)
    invoices.each do |invoice|
      unless invoice.status == "SENT" || invoice.status == "PAID"
        invoice.update_attribute :status, "SENT"
      end
    end
    
    redirect_to invoices_url
  end
  
  
  def set_paid
    @invoice = Invoice.find(params[:id])
    
    if @invoice.status == "PAID"
        respond_to do |format|
          format.html { redirect_to @invoice, notice: 'Invoice has already been PAID!' }
          format.json { head :no_content }
        end
    else    
      @invoice.update_attribute :status, "PAID"
      flash[:notice] = "Invoice marked '#{@invoice.status}'!"    
      redirect_to @invoice
    end
  end
  
  def set_multiple_paid(invoices)
    invoices.each do |invoice|
      unless invoice.status == "PAID"
        invoice.update_attribute :status, "PAID"
      end
    end
    
    redirect_to invoices_url
  end
  
  def show_pdf    
    @invoice = Invoice.find(params[:id])
    @invoice_items = @invoice.invoice_items
    @client_prices = ClientPrice.where(:client_id => @invoice.client.id)
    
    render :layout => 'pdf_layout'
  end
  
  def generate_pdf
    @invoice = Invoice.find(params[:id])
    path = show_pdf_invoice_url(@invoice)
    filename = "invoice_#{@invoice.id}"
    
    kit = PDFKit.new(path)
    pdf = kit.to_pdf
    send_data(pdf, :filename => filename, :type => 'application/pdf', :disposition => 'inline')
  end
  
  def generate_multiple_pdfs
    @invoices = Invoice.find(params[:selected_invoices])
    
    if params[:commit] == "Print Labels"      
      render :labels, :layout => 'labels_layout'
    elsif params[:commit] == "Set Sent" || params[:commit] == "Set Paid"
        if params[:commit] == "Set Sent"
          set_multiple_sent(@invoices)
        else
          set_multiple_paid(@invoices)
        end
    else
      files = []
      @invoices.each do |invoice|
        path = show_pdf_invoice_url(invoice)
        filename = "invoice_#{invoice.id}.pdf"
        files.push filename    

        kit = PDFKit.new(path)
        pdf = kit.to_file("#{Rails.root}/public/invoices/#{filename}")
      end
    


      #Combine generated PDFs into single file
      pdf_pack = CombinePDF.new
      files.each do |file|
        pdf_pack << CombinePDF.load("#{Rails.root}/public/invoices/#{file}")
      end
      pack_filename = "invoices_#{Date.today.to_formatted_s(:iso8601)}.pdf"
      pdf_pack.save "#{Rails.root}/public/invoices/#{pack_filename}"

      send_file("#{Rails.root}/public/invoices/#{pack_filename}", :type => 'application/pdf')
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def sort_column
      params[:sort] || "date"
    end

    def sort_direction
      params[:direction] || "desc"
    end


    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:date, :performed_by, :status, :note, :client_id, :client_lastname, :ids, :selected_invoices)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, :default => Date.today  %>
  </div>
  <div class="field">
    <%= f.label :performed_by %><br>
    <%= f.text_field :performed_by, required: true %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :client %><br>
    <%= f.text_field :client_name, data: {autocomplete_source: Client.order(:last_name).map{ |m| {:label=>m.client_summary, :id=>m.id}}}, required: true %>
    <%= f.hidden_field :client_id %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/_neg_balance.html.erb
<strong>Payment Received:</strong> <%= number_to_currency(@invoice.client.last_payment) %>
<br>
<strong>Amount due:</strong> <%= number_to_currency(@invoice.client.balance) %>

app/views/invoices/_pos_balance.html.erb
<strong>Balance forward:</strong> <%= number_to_currency(@invoice.balance_forward) %>
<br>
<strong>Amount due:</strong> <%= number_to_currency(@invoice.amount_due) %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h1>Listing Invoices</h1>
    <div class="pull-right range-query">
    <%= form_tag invoices_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'Search', class: 'btn search-button'%>
    <% end %> 
  </div>
</div>

<%= link_to 'New Invoice', new_invoice_path %>

<div class="media">
  <div class="media-body">
    <%= form_tag generate_multiple_pdfs_invoices_path, method: :get do %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><input type="checkbox" id="selectAll" value="selectAll"></th>
          <th><%= sortable "date" %></th>
          <th><%= sortable "id", "Name" %></th>
          <th><%= sortable "performed_by" %></th>
          <th><%= sortable "status" %></th>
          <th>Note</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td><%= check_box_tag "selected_invoices[]", invoice.id %></td>
            <td><%= invoice.date.strftime("%m-%d-%y") %></td>
            <td><%= invoice.client.first_name %> <%= invoice.client.last_name %> </td>
            <td><%= invoice.performed_by %></td>
            <td><%= invoice.status %></td>
            <td><%= invoice.note %></td>
            <td><%= link_to 'Show Invoice', invoice, class: 'btn btn-mini btn-success' %></td>
          </tr>
        <% end %>
      </tbody>
    </table> 
      <div class='btn-group'>
        <%= submit_tag "Print Selected Invoices", class: 'btn btn-primary' %>
        <%= submit_tag "Print Labels", class: 'btn btn-primary' %>
        <%= submit_tag "Set Sent", class: 'btn btn-primary' %>
        <%= submit_tag "Set Paid", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<br>

<script>
  $('#selectAll').click(function() {
     if (this.checked) {
         $(':checkbox').each(function() {
             this.checked = true;                        
         });
     } else {
        $(':checkbox').each(function() {
             this.checked = false;                        
         });
     } 
  });
</script>

app/views/invoices/labels.html.erb
<% @invoices.each do |label| %>
  <div class="label">
    <%= label.client.first_name %> <%= label.client.last_name %> <br>
    <%= label.client.billing_address %> <br>
    <%= label.client.city %>, <%= label.client.state %> <%= "#{label.client.zip}".rjust(5, '0') %>  
  </div>
<% end %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date.strftime("%m-%d-%y") %>
</p>

<p>
  <strong>Performed by:</strong>
  <%= @invoice.performed_by %>
</p>

<p>
  <strong>Status:</strong>
  <%= @invoice.status %>
</p>

<p>
  <strong>Note:</strong>
  <%= @invoice.note %>
</p>

<p>
  <strong>Client:</strong>
  <%= @invoice.client.first_name %> <%= @invoice.client.last_name %>
</p>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Service</th>
          <th>Category</th>
          <th>Quantity</th>
          <th>Cost</th>
          <th>Total</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @invoice_items.each do |item| %>
        <tr>
          <% if item.name.downcase == 'cut' %>
            <td><h4><%= @invoice.date.strftime( "%B" ) %> Lawncare</h4></td>
            <% else %>
            <td><h4><%= item.name %></h4></td>
            <%end %>            
            <td><h4><%= item.category  %></h4></td>
            <td><h4><%= item.quantity %></h4></td>
            <td><h4><%= number_to_currency(item.price) %> </h4></td>
            <td><h4><%= number_to_currency(item.price * item.quantity) %> </h4></td> 
            <td><h4><%= link_to "Delete", [@invoice, item], method: :delete, confirm: "Are you sure you want to delete this item?" %></h4></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to "Add new item", new_invoice_invoice_item_path(@invoice), class: 'pull-right' %>

<br>

<h4 class='pull-right'> Invoice total: <%= number_to_currency(@invoice.total) %> </h4>

<br><br>

<div class='pull-right btn-group'> 
  <%= link_to "Set Status to Sent", set_sent_invoice_path(@invoice), class: 'btn btn-default' %>
  <%= link_to "Set Status to Paid", set_paid_invoice_path(@invoice), class: 'btn btn-default'%>
</div>

<div class='btn-group'>
  <%= link_to 'Edit Details', edit_invoice_path(@invoice), class: 'btn btn-primary' %>
  <%= link_to 'Back', invoices_path, class: 'btn btn-primary' %>
  <%= link_to "Generate PDF", generate_pdf_invoice_path(@invoice), class: 'btn btn-primary' %>
</div>

<div>
<%= link_to 'Delete Invoice', @invoice, method: :delete, class: 'pull-right btn btn-danger', data: { confirm: "This is a permanent action that can't be reversed. Are you sure?" } %>
</div>

app/views/invoices/show.pdf.erb
<p id="notice"><%= notice %></p>

app/views/invoices/show_pdf.html.erb
<div>
  <div>
    <p>
      <h2> <u>Moffa Landscaping</u>
        </h2>
      27 Bryant Street<br>
      Revere, MA 02151
      </p>
  </div>
  <br>
  <h3> 
    Invoice
    </h3>
  <br>
  <div class="pull-left" style="width:33%">
    <p> 
      <%= @invoice.client.first_name %> <%= @invoice.client.last_name %> <br>
      <%= @invoice.client.billing_address %> <br>
      <%= @invoice.client.city %>, <%= @invoice.client.state %> <%= "#{@invoice.client.zip}".rjust(5, '0') %>   
      </p>
    </div>

  <div class="pull-right" style="width:33%">
    <p> 
      <strong>Invoice number:</strong> <%= @invoice.id %> <br>
      <strong>Invoice date:</strong> <%= @invoice.date.strftime("%m-%d-%y") %> <br>
      <strong>Payment due by:</strong> <%= (@invoice.date + (14*24*60*60)).strftime("%m-%d-%y") %>
      </p>
    </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <div>
    <p>
      <strong>Notes:</strong>
      <%= @invoice.note %>
      </p>
    <br>
    <div class="panel panel-default" >
      <div class="panel-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Service</th>
              <th>Category</th>
              <th>Quantity</th>
              <th>Cost</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>
            <% @invoice_items.each do |item| %>
            <tr>
              <% if item.name.downcase == 'cut' %>
                <td><h4><%= @invoice.date.strftime( "%B" ) %> Lawncare</h4></td>
                <% else %>
                <td><h4><%= item.name %></h4></td>
                <%end %>            
                <td><h4><%= item.category  %></h4></td>
                <td><h4><%= item.quantity %></h4></td>
                <td><h4><%= number_to_currency(item.price) %> </h4></td>
                <td><h4><%= number_to_currency(item.price * item.quantity) %> </h4></td>
              </tr>
            <% end %> 
          </tbody>
        </table>      
        <br>
        <h4 class='pull-right' align='right'>
          <strong>Invoice subtotal:</strong> <%= number_to_currency(@invoice.total) %>
          <br>
          <%= render partial: @invoice.check_balance_forward, :locals => {invoice: @invoice} %>
        </h4>
      </div>
    </div>
  </div>
  
  <h4>Please make checks payable to: Aurelio Moffa, P.O. Box 555, Revere, MA 02151. If you have any questions please call 781-526-2967.</h4>

</div>