config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  
  devise_scope :user do
    authenticated do
      root to: "clients#index"
    end
    
    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end
  
  resources :estimates do
    resources :estimate_items, except: [:index], controller: 'estimates/estimate_items'
    member do
      get :estimate_pdf
      get :view_estimate_pdf
    end
    collection { get :generate_estimate_pdfs }
  end
  
  resources :payments
  resources :services
  
  resources :clients do
    member do
      get :reminder
    end

    collection do
      post :import
      get :summary
      get :generate_reminders
      get :reminder_labels
    end
    
    resources :client_prices, except: [:index], controller: 'clients/client_prices' do
      collection { post :import }
    end
    
  end
  
  resources :invoices do
    resources :invoice_items, except: [:index], controller: 'invoices/invoice_items'
    member do
      put :set_sent
      put :set_paid
      get :show_pdf
      get :generate_pdf
    end
    collection do
      get :generate_multiple_pdfs
      get :labels
    end
  end
  
  resources :client_prices, controller: 'clients/client_prices' do
    collection { post :import }
  end
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :billing_address, :job_address, :city, :balance, presence: true
  validates :state, presence: true,
                    format: {with: /\A([A-Z]+)\z/, message: "Only allows letters"},
                    length: {is: 2}
  validates :zip, presence: true,
                  format: {with: /\A([0-9]+)\z/, message: "Only allows numbers"},
                  length: {is: 5}
  
  self.primary_key = 'id'
  has_many :invoices, dependent: :destroy
  has_many :invoice_items, through: :invoices
  has_many :client_prices, dependent: :destroy
  has_many :services, through: :client_prices
  
  searchable do
    text :id
    text :first_name
    text :last_name
    text :job_address
    text :billing_address
    text :city
    string :first_name
    string :last_name
    string :id
  end
  
  def full_name
    [first_name, last_name].each{|e| e.to_s.strip!}.join(' ')
  end
  
  def client_summary
    [full_name, job_address].each{|e| e.to_s.strip!}.join(' - ')
  end    

  def last_payment
    payment = Payment.where(:client_id => id).scoping do
      Payment.last
    end
    if payment == nil
      " "
    else
      payment.amount
    end
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Client.create! row.to_hash
    end
  end
  
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |client|
        csv << client.attributes.values_at(*column_names)
      end
    end
  end
  
end

app/controllers/clients/client_prices_controller.rb
class Clients::ClientPricesController < ApplicationController

  def index
    @client_prices = ClientPrice.all
  end

  def show
  end

  def new
    @client = Client.find(params[:client_id])
    @client_price = ClientPrice.new
    @services = Service.all
  end

  def edit
  end


  def create
    @client = Client.find(params[:client_id])
    @client_price = ClientPrice.new(client_price_params)
    @client_price.client_id = @client.id

    respond_to do |format|
      if @client_price.save
        format.html { redirect_to @client, notice: 'Service was successfully added to client.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @client_price.update(client_price_params)
        format.html { redirect_to @client_price, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_price }
      else
        format.html { render :edit }
        format.json { render json: @client_price.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @client = Client.find(params[:client_id])
    @client_price = ClientPrice.find(params[:id])
        
    title = @client_price.name
    
    if @client_price.destroy
      flash[:notice] = "#{title} was deleted succesfully."
      redirect_to @client
    else
      flash[:error] = "There was an error deleting the service."
      render :show
    end
  end

  def import
    ClientPrice.import(params[:file])
    redirect_to clients_path, notice: "Client prices added succesfully"
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_price
      @client_price = ClientPrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_price_params
      params.require(:client_price).permit(:price, :clients_id, :service_id, :name)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_user!, except: [:reminder, :generate_reminders]
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  # GET /clients
  # GET /clients.json
  def index
    @search = Client.search do
      fulltext params[:search]
      order_by(:id, :asc)
      paginate(:page => params[:page] || 1, :per_page => 30)
    end
    @clients = @search.results
      
    
#    @clients = Client.all
#    if params[:search]
#      @clients = Client.search(params[:search]).order(sort_column + " " + sort_direction)
#    else
#      @clients.order(sort_column + " " + sort_direction)
#    end
    
  respond_to do |format|
      format.html
      format.csv do
        @clients = Client.all
        render text: @clients.to_csv
      end        
    end
  end

  def show
    @client = Client.find(params[:id])
    @client_prices = @client.client_prices
    @services = Service.all
    @invoices = Invoice.where(:client_id => params[:id]).limit(5).order(date: :desc)
    @payments = Payment.where(:client_id => params[:id]).limit(5).order(date: :desc)
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)
    @client.balance = 0
        
    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    Client.import(params[:file])
    redirect_to clients_path, notice: "Clients added succesfully!"
  end

  def summary
    @clients = Client.all.order(id: :asc)
    
    render :layout => 'pdf_layout'
  end

  def reminder
    @client = Client.find(params[:id])
    @date = Date.today.strftime('%m/%d/%Y')

    render layout: 'pdf_layout'
  end

  def generate_reminders
    @clients = Client.where('CAST(balance AS numeric) > ?', 0.0)

    reminders = []
    @clients.each do |client|
      path = reminder_client_url(client)
      filename = "#{client.last_name}_reminder_#{Time.current.strftime('%Y%m%d')}.pdf"
      reminders << filename

      kit = PDFKit.new(path)
      pdf = kit.to_file("#{Rails.root}/reminders/#{filename}")
    end

    pdf_pack = CombinePDF.new
    reminders.each do |reminder|
      pdf_pack << CombinePDF.load("#{Rails.root}/reminders/#{reminder}")
    end
    pack_filename = "reminders_#{Date.today.to_formatted_s(:iso8601)}.pdf"
    pdf_pack.save "#{Rails.root}/reminders/#{pack_filename}"

    send_file("#{Rails.root}/reminders/#{pack_filename}", :type => 'application/pdf')
  end

  def reminder_labels
    @clients = Client.where('CAST(balance AS numeric) > ?', 0.0)

    render layout: 'labels_layout'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def sort_column
      params[:sort] || "id"
    end

    def sort_direction
      params[:direction] || "asc"
    end    

    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :billing_address, :job_address, :city, :state, :zip)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, required: true %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, required: true %>
  </div>
  <div class="field">
    <%= f.label :billing_address %><br>
    <%= f.text_field :billing_address, required: true %>
  </div>
  <div class="field">
    <%= f.label :job_address %><br>
    <%= f.text_field :job_address, required: true %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, required: true %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state, required: true %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip, required: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>
<br>
  <div class="pull-right">
    <%= form_tag(clients_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Clients" %>
    <%= submit_tag "Search", class: 'btn search-button' %>
    <% end %>
  </div>
<br>
<%= link_to 'Add New Client', new_client_path, class: 'btn btn-primary' %> |
<%= link_to 'Print Client List', summary_clients_path, class: 'btn btn-primary'%> |
<%= link_to 'Print Reminders', generate_reminders_clients_path, class: 'btn btn-primary'%> |
<%= link_to 'Print Reminder Labels', reminder_labels_clients_path, class: 'btn btn-primary'%>
<br>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th><%= sortable "billing_address" %></th>
          <th><%= sortable "job_address" %></th>
          <th><%= sortable "city" %></th>
          <th><%= sortable "state" %></th>
          <th><%= sortable "zip" %></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td><%= client.first_name %> <%= client.last_name %></td>
            <td><%= client.billing_address %></td>
            <td><%= client.job_address %></td>
            <td><%= client.city %></td>
            <td><%= client.state %></td>
            <td><%= "#{client.zip}".rjust(5, '0') %></td>
            <td><%= link_to 'Details', client, class: 'btn btn-mini btn-default' %></td>
            <td><%= link_to 'Edit', edit_client_path(client), class: 'btn btn-mini btn-success' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
  </div>
  
  <%= will_paginate @clients %>
</div>

<br>

<h3>Import Clients</h3>
<%= form_tag import_clients_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Clients", class: 'btn btn-default' %>
<% end %>

<h3>Import Client Prices</h3>
<%= form_tag import_client_prices_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Prices", class: 'btn btn-default' %>
<% end %>

<h3>Download client records</h3>
<%= link_to "Download", clients_path(format: "csv"), class: 'btn btn-default' %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/reminder.html.erb
<div>
  <p>
    <h2>
     Moffa Landscaping
    </h2>
    27 Bryant Street<br>
    Revere, MA 02151
  </p>
</div>
<br>

<div>
  <p>
    <b><%= @client.full_name %></b><br>
    <%= @client.billing_address %><br>
    <%= @client.city %>, <%= @client.state %> <%= @client.zip %>
  </p>
</div>
<br>

<p>Valued Client,</p>
<br>

<p>You are receiving this letter because you have an outstanding balance
  according to our records. We would greatly appreciate it if you could pay
  your balance before the beginning of the next season.</p>

<p>Your outstanding balance as of <%= @date %> is:</p>

<div class='center-balance'><h3><%= number_to_currency(@client.balance) %></h3></div>
<br>


<p>If you believe you've received this letter in error, or if you have any questions,
  please feel free to call us at 781-289-1483 or 781-526-2967.</p>

<br>
<br>
<br>
<br>
<br>
<br>
<p>Thank you,</p>
<p><b>Moffa Landscaping</b></p>

app/views/clients/reminder_labels.html.erb
<% @clients.each do |label| %>
    <div class="label">
      <%= label.first_name %> <%= label.last_name %> <br>
      <%= label.billing_address %> <br>
      <%= label.city %>, <%= label.state %> <%= "#{label.zip}".rjust(5, '0') %>
    </div>
<% end %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<div style="display: flex;">
  <div style="flex: 1;">
    <p>
      <strong>First name:</strong>
      <%= @client.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @client.last_name %>
    </p>

    <p>
      <strong>Billing address:</strong>
      <%= @client.billing_address %>
    </p>

    <p>
      <strong>Job address:</strong>
      <%= @client.job_address %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @client.city %>
    </p>

    <p>
      <strong>State:</strong>
      <%= @client.state %>
    </p>

    <p>
      <strong>Zip:</strong>
      <%= "#{@client.zip}".rjust(5, '0') %>
    </p>
  </div>

  <div style="flex: 1;">  
    <p>
      <strong>Balance:</strong>
      <%= number_to_currency(@client.balance) %>
    </p>
  </div>
</div>


<div>
  <div class="media" >
    <div class="media-body" style="width: 50%; float: left;">
      <h3>Recent invoices:</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th><h4>ID</h4></th>
            <th><h4>Date</h4></th>
            <th><h4>Amount</h4></th>
          </tr>
        </thead>
        <tbody>
          <% @invoices.each do |invoice| %>
          <tr>
            <td><h4><%= invoice.id %></h4></td>
            <td><h4><%= invoice.date.strftime("%m-%d-%y") %></h4></td>
            <td><h4><%= number_to_currency(invoice.total) %></h4></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="media-body" style="width: 50%; float: right;">
      <h3>Recent payments:</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <td><h4>ID</h4></td>
            <td><h4>Date</h4></td>
            <td><h4>Amount</h4></td>
          </tr>
        </thead>
        <tbody>
          <% if @payments.blank? %>
            <tr>
              <td><h4>No recent payments to show</h4></td>
              <td></td>
              <td></td>
            </tr>
          <% else %>
            <% @payments.each do |payment| %>
            <tr>
              <td><h4><%= payment.id %></h4></td>
              <td><h4><%= payment.date.strftime("%m-%d-%y") %></h4></td>
              <td><h4><%= number_to_currency(payment.amount) %></h4></td>
            </tr>
            <% end %>
          <% end %> 
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="media" style="clear: both;">
  <div class="media-body">
    <h3 style="align:left;">Current services for client:</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><h4>Service</h4></th>
          <th><h4>Price</h4></th>
          <th><h4></h4></th>
        </tr>
      </thead>
      <tbody>
        <% @client_prices.each do |item| %>
        <tr>
          <td><h4><%= item.name %></h4></td>
          <td><h4><%= number_to_currency(item.price) %></h4></td>
          <td><h4><%= link_to "Remove Service", [@client, item], class:'btn btn-mini btn-default', method: :delete, confirm: "Are you sure you want to remove this service from the customer?" %></h4></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<br>

<div class='btn-group' style="width: 80%">
  <%= link_to 'Edit Client Details', edit_client_path(@client), class: 'btn btn-primary' %> 
  <%= link_to "Add New Service", new_client_client_price_path(@client), class: 'btn btn-primary'%> 
  <%= link_to 'Back', clients_path, class: 'btn btn-primary'%>
</div>

<%= link_to 'Delete Client', @client, method: :delete, class: 'pull-right btn btn-danger', data: { confirm: "This is a permanent actiong that can't be reversed. You will lose ALL CLIENT RECORDS! Are you sure?" } %>

app/views/clients/summary.html.erb
<div class="media">
  <div class="media-body"> 
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Job Address</th>
          <th>Balance</th>
          <th>Last Payment Recieved</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      
      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td><%= client.id %></td>
            <td><%= client.full_name %></td>
            <td>
              <%= client.job_address %><br>
              <%= client.city%>, <%= client.state %> <%= client.zip %>
            </td>
            <td><%= client.balance %></td>
            <td><%= client.last_payment %></td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>